### ISSUE TITLE
Integer multiple error

### ISSUE THREAD

**Issue by jojano5** [FZJ-IEK3-VSA/tsam#47]
Dear Mr @l-kotzur,

Part of my masters thesis is to reduce the size of the input data of an energy system without loosing the peaks! I would like to use tsam to do it.
I do not have much reliable data so right now I am working with **one month data** with a **minutely resolution** which means that the length of the time series is **43200**. It is already normalized!
My goal is to aggregate the data into **15 min** using the peak integration. 
I am trying to run the package functions but for some lack of knowledge and misunderstanding I simply can`t run it. 

My question is: In the case that I want to aggregate the data into 15 min, What would be the number of typical periods and the hours per period?

I`m using the following which throws me an error of integer multiple. 2880 typical periods because there are 2880 15min in 30 days
```
aggregation = tsam.TimeSeriesAggregation(ts, 
						noTypicalPeriods = 2880, 
						hoursPerPeriod =  15, 
						clusterMethod = 'k_means')

ValueError: The combination of hoursPerPeriod and the resulution does 
not result in an integer number of time steps per period
```

**Comment by maximilian-hoffmann** [comment]
Dear Mr. Rodriguez (@jojano5 ),

we feel honored that you are planning to use our software.
Tsam is a tool for clustering time series to irregular time step lengths and typical periods - for a detailed overview, see the following publiction: https://www.mdpi.com/1996-1073/13/3/641

As you are planning to turn every 15 time steps (your minutes) into one large time step, use the segmentation tool instead. This task is only a downsampling task, not a clustering task. The parameters to choose are:

noTypicalPeriods = 2880
horusPerPeriod = 0.25 (since your periods are a quarter of an hour. There will be an error in line 438 - simply comment this checking method out)
clusterMethod does not need to be set, but set it to hierarchical - it's likely faster
segmentation = True
noSegments = 1 (per period consisting of 15 minutely time steps)

I really hope this helps.
Kind regards,
Max

**Comment by jojano5** [comment]
Dear Mr Hoffmann (@maximilian-hoffmann ),

**Comment by maximilian-hoffmann** [comment]
Dear Mr. Rodriguez (@jojano5 ),
as mentioned above, simply comment the checking mehtod within tsam in timeseriesaggregation.py in line 438 out. If you don't now how to make changes in the tsam code itself, uninstall tsam, clone it to a place of your convenience and install it via `pip install -e .`. Then, you can make the changes in the tsam folder as you wish.
Kind regards,
Max

**Comment by jojano5** [comment]
Dear Mr. Hoffmann

I will try to debug it because I am still getting an error

`ValueError: The combination of hoursPerPeriod and the resulution does not result in an integer number of time steps per period. 
`
kind regards 

Joan
